# Generated by Django 4.1 on 2024-05-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                ("hospital_id", models.AutoField(primary_key=True, serialize=False)),
                ("hospital_name", models.CharField(max_length=100)),
                ("hospital_address", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("tckn", models.CharField(max_length=12)),
                ("date_of_birth", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=10)),
                ("tel_no", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="page.hospital"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("tckn", models.CharField(max_length=12)),
                ("date_of_birth", models.CharField(max_length=50)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="page.hospital"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("doctor_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("tckn", models.CharField(max_length=12)),
                ("date_of_birth", models.CharField(max_length=50)),
                ("profession", models.CharField(max_length=50)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="page.hospital"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                ("appointment_date", models.CharField(max_length=50)),
                ("appointment_time", models.CharField(max_length=50)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="page.doctor"
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="page.hospital"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="page.patient"
                    ),
                ),
            ],
        ),
    ]
